In [58]:
import numpy as np

# De functie die gebruikt wordt om de output van de neuronen te berekenen
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)


In [59]:
# Training inputdata en verwachte output
training_inputs = np.array([[0, 0, 0, 1], 
                            [1, 1, 1, 1], 
                            [1, 0, 1, 0], 
                            [0, 1, 0, 1]])
training_outputs = np.array([[0, 1, 1, 0]]).T

In [60]:
np.random.seed(1)
# Gewichten tussen de inputlaag en de verborgen laag
synaptic_weights_input_hidden = 2 * np.random.random((4, 4)) - 1
# Gewichten tussen de verborgen laag en de uitvoerlaag
synaptic_weights_hidden_output = 2 * np.random.random((4, 1)) - 1

print('Random startgewichten: ')
print(synaptic_weights_input_hidden)
print('Random outputgewichten: ')
print(synaptic_weights_hidden_output)

Random startgewichten: 
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]
 [-0.5910955   0.75623487 -0.94522481  0.34093502]]
Random outputgewichten: 
[[-0.1653904 ]
 [ 0.11737966]
 [-0.71922612]
 [-0.60379702]]


In [61]:
for i in range(20000):
    # Voorwaartse propagatie
    input_layer = training_inputs
    hidden_layer_input = np.dot(input_layer, synaptic_weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, synaptic_weights_hidden_output)
    outputs = sigmoid(output_layer_input)

    error = training_outputs - outputs

    output_adjustments = error * sigmoid_derivative(outputs)

    # Backpropagatie naar de hidden layer
    hidden_error = np.dot(output_adjustments, synaptic_weights_hidden_output.T)
    hidden_adjustments = hidden_error * sigmoid_derivative(hidden_layer_output)

    # Aanpassen van de gewichten
    synaptic_weights_hidden_output += np.dot(hidden_layer_output.T, output_adjustments)
    synaptic_weights_input_hidden += np.dot(input_layer.T, hidden_adjustments)

#alle resultaten printen
print('Gewichten voor de hidden layer: ')
print(synaptic_weights_input_hidden)
print('Gewichten voor de output: ')
print(synaptic_weights_hidden_output)

print('Output: ')
print(outputs)

print('Afgeronde output: ')
print(np.round(outputs).astype(int))

print('Trainingsoutput: ')
print(training_outputs)


Gewichten voor de hidden layer: 
[[-0.24139693  2.66607982 -2.54895196 -2.63370043]
 [-0.70751973 -0.57432138 -0.13852732 -0.40442554]
 [-0.28190599  2.3030643  -1.71079168 -1.86792657]
 [-0.55267478 -1.36614856  1.50566603  1.90350378]]
Gewichten voor de output: 
[[ 0.04025336]
 [ 6.05837266]
 [-3.96674424]
 [-4.37470205]]
Output: 
[[0.00299547]
 [0.995364  ]
 [0.997344  ]
 [0.00255439]]
Afgeronde output: 
[[0]
 [1]
 [1]
 [0]]
Trainingsoutput: 
[[0]
 [1]
 [1]
 [0]]
